# Generated by Django 4.1 on 2022-08-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_name_playlist_playlist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='name',
            new_name='track_name',
        ),
    ]
