# Generated by Django 4.1 on 2022-08-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_track_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.PositiveIntegerField(),
        ),
    ]
