# Generated by Django 4.1 on 2022-09-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_track_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='slug',
        ),
    ]
