# Generated by Django 4.1 on 2022-09-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_track_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='song',
            field=models.FileField(blank=True, upload_to='mp3'),
        ),
    ]
